os: linux

services:
  - docker

language: python
python: 3.6

install:
  - pip install cwl-runner cwltest cwltool
  - docker build -t annotation:latest $TRAVIS_BUILD_DIR/CWL/Tools/Annotation/
  - docker build -t assign:latest $TRAVIS_BUILD_DIR/CWL/Tools/Assign/
  - docker build -t hmmscan:latest $TRAVIS_BUILD_DIR/CWL/Tools/HMMScan/
  - docker build -t cwl_length_filter_docker:latest $TRAVIS_BUILD_DIR/CWL/Tools/LengthFiltering/
  - docker build -t mapping:latest $TRAVIS_BUILD_DIR/CWL/Tools/Mapping/
  - docker build -t cwl_parse_pred:latest $TRAVIS_BUILD_DIR/CWL/Tools/ParsingPredictions/
  - docker build -t prodigal:latest $TRAVIS_BUILD_DIR/CWL/Tools/Prodigal/
  - docker build -t ratio_evalue:latest $TRAVIS_BUILD_DIR/CWL/Tools/RatioEvalue/
  - docker build -t sed_docker:latest $TRAVIS_BUILD_DIR/CWL/Tools/Sed/
  - docker build -t virfinder:latest $TRAVIS_BUILD_DIR/CWL/Tools/VirFinder/
  - docker build -t simroux/virsorter:v1.0.5 $TRAVIS_BUILD_DIR/CWL/Tools/VirSorter/

script:
  - source $TRAVIS_BUILD_DIR/venv/bin/activate;
  - cwltest --test $TRAVIS_BUILD_DIR/CWL/Tests/pipeline_test.yml  --verbose
