os: linux

services:
  - docker

language: python
python: 3.6

install:
  - bash $TRAVIS_BUILD_DIR/hmm_db/setup.sh
  - docker build -t mgnify/kegg2hmm $TRAVIS_BUILD_DIR/hmm_db/container

script:
  - source $TRAVIS_BUILD_DIR/venv/bin/activate;
  - cwltest --test $TRAVIS_BUILD_DIR/hmm_db/tests/cwl/test_hmm_workflow.yml  --verbose
