os: linux

services:
  - docker

language: python
python: 3.6

install:
  - pip install cwl-runner cwltest cwltool
  - mkdir $TRAVIS_BUILD_DIR/virsorter-data-cache
  - wget -nc -q -P $TRAVIS_BUILD_DIR/virsorter-data-cache/ https://zenodo.org/record/1168727/files/virsorter-data-v2.tar.gz
  - tar -xvzf $TRAVIS_BUILD_DIR/virsorter-data-cache/virsorter-data-v2.tar.gz
  - mv $TRAVIS_BUILD_DIR/virsorter-data $TRAVIS_BUILD_DIR/CWL/Tools/VirSorter/

  - docker pull simroux/virsorter:v1.0.5
  - docker pull mgnify/hmmscan:latest

  - docker build -q -t virfinder_viral:latest $TRAVIS_BUILD_DIR/CWL/Tools/VirFinder/
  - docker build -q -t annotation_viral_contigs:latest $TRAVIS_BUILD_DIR/CWL/Tools/Annotation/
  - docker build -q -t assign_taxonomy:latest $TRAVIS_BUILD_DIR/CWL/Tools/Assign/
  - docker build -q -t cwl_length_filter_docker:latest $TRAVIS_BUILD_DIR/CWL/Tools/LengthFiltering/
  - docker build -q -t mapping_viral_predictions:latest $TRAVIS_BUILD_DIR/CWL/Tools/Mapping/
  - docker build -q -t cwl_parse_pred:latest $TRAVIS_BUILD_DIR/CWL/Tools/ParsingPredictions/
  - docker build -q -t prodigal_viral:latest $TRAVIS_BUILD_DIR/CWL/Tools/Prodigal/
  - docker build -q -t ratio_evalue:latest $TRAVIS_BUILD_DIR/CWL/Tools/RatioEvalue/
  - docker build -q -t sed_docker:latest $TRAVIS_BUILD_DIR/CWL/Tools/Sed/

script:
  - cwltest --test $TRAVIS_BUILD_DIR/CWL/Tests/pipeline_test.yml  --verbose --timeout 36000

cache:
  directories:
  -
deploy:
  provider: script
  script: bash $TRAVIS_BUILD_DIR/docker_push.sh
  on:
    branch: master