os: linux

services:
  - docker

language: python
python: 3.6

install:
  - pip install -q cwl-runner cwltest cwltool
  - sudo apt-get install aria2
  - mkdir -p $TRAVIS_BUILD_DIR/virsorter-data-cache

  - >
    (aria2c -x 16 -s 16 --dir=$TRAVIS_BUILD_DIR/virsorter-data-cache/ ftp://ftp.ebi.ac.uk/pub/databases/metagenomics/VirSorter_data_viral/virsorter-data-v2.tar.gz &&
    tar -xvzf $TRAVIS_BUILD_DIR/virsorter-data-cache/virsorter-data-v2.tar.gz) &
    docker build -q -t cwl_length_filter_docker:latest $TRAVIS_BUILD_DIR/CWL/Tools/LengthFiltering/ &
    docker pull simroux/virsorter:v1.0.5 &
    docker pull mgnify/virfinder_viral:latest &
    docker build -q -t cwl_parse_pred:latest $TRAVIS_BUILD_DIR/CWL/Tools/ParsingPredictions/
    ; wait
  - mv $TRAVIS_BUILD_DIR/virsorter-data $TRAVIS_BUILD_DIR/CWL/Tools/VirSorter/

script:
  - echo -e '#!/bin/bash\ncwltool --parallel "$@"' > pcwltool
  - chmod a+x pcwltool
  - export PATH=$PATH:$PWD && travis_wait 60 cwltest --test $TRAVIS_BUILD_DIR/CWL/Tests/test_pipeline_4steps.yml --timeout 7200 --tool pcwltool
  # $TRAVIS_BUILD_DIR/CWL/Tests/pipeline_test.yml --timeout 7200 --tool pcwltool


# Caching from https://github.com/travis-ci/travis-ci/issues/5358#issuecomment-248915326
before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

cache:
  bundler: true
  directories:
    - $HOME/docker
    - $TRAVIS_BUILD_DIR/virsorter-data-cache/

deploy:
  provider: script
  script: bash $TRAVIS_BUILD_DIR/docker_push.sh
  on:
    branch: master