input_fasta_file:
  class: File
  path: ../ERR575691_host_filtered.fasta
length_length_filter: 0.5
output_file_virfinder:  output.tsv
input_data_dir_virsorter:
  class: Directory
  path: /Users/kates/virsorter/virsorter-data/
input_virsorter_dir:
  class: Directory
  path: .
input_prodigal_procedure: meta
input_name_output_prophages: File_viral_CDS.faa
